
version: 2

models:
  - name: stg_shoppers
    description: "Shoppers dimension."
    columns:
      - name: shopper_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: age
        description: "Customer age (integer)."

  - name: stg_orders
    description: "Table containing orders and loan obligations (principal and fees)."
    columns:
      - name: order_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: shopper_id
        description: "Unique customer identifier."
        data_tests:
          - not_null
          - relationships:
              to: ref('stg_shoppers')
              field: shopper_id
      - name: order_date
        description: ""
        data_tests:
          - not_null
      - name: product_id
        description: "Product identifier."
      - name: merchant_id
        description: "Merchant identifier."
      - name: is_in_default
        description: "Boolean field to know if the loan is in arrears."
      - name: days_unbalanced
        description: "Number of days (integer). If field is greater than 0 means that the loan is in arrears."
      - name: current_order_value
        description: "The amount of money of an order (loan)."
      - name: overdue_principal
        description: "Unpaid principal."
      - name: overdue_fees
        description: "Unpaid fees."

  - name: stg_default_order_type
    description: "Table with default categorization."
    columns:
      - name: default_type_id
        description: "The primary key for this table."
      - name: order_id
        description: "Foreign key to stg_orders table."
        tests:
          - not_null

